# mail_title: 'Daily ArXiv Papers Alert'
smtp_host: 'smtp.163.com'
smtp_port: 465
sender: xxx1@163.com
sender_password: xxx
receivers: ['xxx2@163.com']
categories: ['cs.ai', 'cs.cv', 'cs.cl', 'cs.lg', 'stat.ml']
keywords: ['diffusion', 'image generation']
authors: []
max_results: 50
